wandb_version: 1

batchsize:
  desc: null
  value: 128
epochs:
  desc: null
  value: 20
latentdim:
  desc: null
  value: 1024
numsamples:
  desc: null
  value: 145437
data:
  desc: null
  value: ./Data/Cat-Eng/cat.txt
celltype:
  desc: null
  value: LSTM
optimizer:
  desc: null
  value: rmsprop
layers:
  desc: null
  value: 1
dropouts:
  desc: null
  value: 0
learingrate:
  desc: null
  value: 0.0001
validationsplit:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.17.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715780344
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 16
      - 23
      4: 3.11.0
      5: 0.17.0
      8:
      - 3
      - 5
      13: windows-amd64
